name: Prepare a Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version to be released"
        required: true

jobs:
  prepare-for-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Hatch
        run: python -m pip install hatch

      - name: Update Package Version
        run: hatch version ${{ github.event.inputs.version }}

      - name: Update Changelog
        run: hatch run changelog:build --yes --version ${{ github.event.inputs.version }}

      - uses: peter-evans/create-pull-request@v4
        name: Create Pull Request
        id: cpr
        with:
          commit-message: "Prepared release ${{ github.event.inputs.version }}"
          branch: "prepare-release/${{ github.event.inputs.version }}"
          title: "Release ${{ github.event.inputs.version }}"
          draft: false
          delete-branch: true
          body: "Automated changes by [prepare_release](.github/workflows/1-prepare-release.yaml) GitHub action."

      - name: Show Pull Request info
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
